version: "3.9"

services:
  llm_api:
    container_name: "llm_api_calm"
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 8008:8008
    environment:
      - DOWNLOAD_MODEL=false
    networks:
      chatbot_network:
        ipv4_address: 192.168.50.2

networks:
  chatbot_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/24
